default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgress-db
  host: localhost
  port: 5433

test:
  <<: *default
  database: postgress-db

production:
  <<: *default
  database: rdb/production.sqlite3
  username: root
  password:
  pool: 5
  timeout: 5000
