default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgress-db
  host: localhost
  port: 5433

test:
  <<: *default
  database: postgress-db

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
