default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5433
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgress-db

test:
  <<: *default
  database: postgress-db

production:
  <<: *default
  database: postgress-db
  username: realtime_search
  password: <%= ENV["DATABASE_URL"] %>
